"""auto update

Revision ID: 5c7c9589cff6
Revises: 
Create Date: 2026-03-27 11:25:10.369396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7c9589cff6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afiliados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('codigo_acesso', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_afiliados_id'), 'afiliados', ['id'], unique=False)
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bancos_id'), 'bancos', ['id'], unique=False)
    op.create_table('categorias_afiliados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_afiliados_id'), 'categorias_afiliados', ['id'], unique=False)
    op.create_table('corretores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('leads_atribuidos', sa.Integer(), nullable=True),
    sa.Column('landing_pages_json', sa.String(), nullable=True),
    sa.Column('codigo_acesso', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corretores_id'), 'corretores', ['id'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dominio', sa.String(), nullable=False),
    sa.Column('proprietario', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('template_mensagem', sa.String(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('leads_total', sa.Integer(), nullable=True),
    sa.Column('conversoes', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_pages_id'), 'landing_pages', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=True),
    sa.Column('valor_pretendido', sa.Float(), nullable=True),
    sa.Column('servico', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('landing_page_id', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('score_estimado', sa.Integer(), nullable=True),
    sa.Column('relacao_parcela_renda', sa.Float(), nullable=True),
    sa.Column('corretor_id', sa.String(), nullable=True),
    sa.Column('historico', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('banco_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('taxa', sa.Float(), nullable=True),
    sa.Column('prazo', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('conteudo_links', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_landing_pages_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_corretores_id'), table_name='corretores')
    op.drop_table('corretores')
    op.drop_index(op.f('ix_categorias_afiliados_id'), table_name='categorias_afiliados')
    op.drop_table('categorias_afiliados')
    op.drop_index(op.f('ix_bancos_id'), table_name='bancos')
    op.drop_table('bancos')
    op.drop_index(op.f('ix_afiliados_id'), table_name='afiliados')
    op.drop_table('afiliados')
    # ### end Alembic commands ###